server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        jdbc:
          lob:
            non-contextual-creation: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.hibernate: DEBUG

  rabbitmq:
    addresses: amqps://sjpxcsel:kzk4tvnpJ3NxleUrF9t3j6k2Q7vvGgVA@beaver.rmq.cloudamqp.com/sjpxcsel
