server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-authuser-v2
    username: postgres
    password: banco123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
  application:
    name: ead-authuser-service
ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course


logging:
  level:
    com.ead: INFO
    org.hibernate: DEBUG

  rabbitmq:
    addresses: amqps://sjpxcsel:kzk4tvnpJ3NxleUrF9t3j6k2Q7vvGgVA@beaver.rmq.cloudamqp.com/sjpxcsel

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 15s
        failure-rate-threshold: 80

  retry:
    instances:
      retryInstance:
        max-attempts: 3
        wait-duration: 5s

